### PR TITLE
fix :fixed profile dropdown in navbar

### LINKED ISSUE #134: Bug: Submenus under My Space > Profile dissappear from Navbar
**Describe the bug**
The submenus under My Space > Profile (Personal Detals, Additional Info, and Personal Background) have dissappeared from the Navbar. One of the recent merged to develop branch is suspected to have caused this.

**To Reproduce**
1. Run the 3 servers (BIT and MS backends as well as BIT frontend)
2. Login and try to update personal details (by going to My Space > Profile > Personal Details on the Navbar)
3. See error (when you click on Profile, dropdown options are not showing)

**Expected behavior**
When you click on Profile, the 3 dropdown options should've been given under the Profile tab instead)

**Screenshots**
with Bug (no options given when Profile is clicked)
Screen Shot 2020-12-13 at 10 39 54 pm

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7
 - Browser: Chrome
 - Version ??

**Additional context**
The submenus options still exists as options under Navigation.js and Route.js. They are just not being displayed when the `Profile` tab is clicked.

### PR DESCRIPTION
**Pull request by chinmaym07**
### Description

Fixes #134 
### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Since it's a UI Bug in the Navbar , It is tested by running it locally.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

Attached a preview of the same fix. 

Peek 2021-01-15 17-19

### CODE REVIEW

**Comment by chinmaym07** [comment]
Hey @mtreacy002 Please review this PR.

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@chinmaym07 , can you please make the changes on a new pr branch (instead of develop branch). It is mentioned in step 4 on the [Getting Started > Start Working](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers/topic/Advice.20Needed/near/223199738) guidelines. Thanks

**Comment by chinmaym07** [comment]
> @chinmaym07 , can you please make the changes on a new pr branch (instead of develop branch). It is mentioned in step 4 on the [Getting Started > Start Working](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers/topic/Advice.20Needed/near/223199738) guidelines. Thanks 

Yes ..sorry ...will rectify that 👍🏻

**Comment by mtreacy002** [comment]
@chinmaym07 , the branch on your repo still shown as develop. perhaps you need to close this PR and open a new one from a new branch.

**Comment by chinmaym07** [comment]
I have opened another pr for this issue so closing this pr..

**Pull request closed without merging**
