### PR TITLE
Feat: Disable gotoprograms/save without org(#86)

### LINKED ISSUE #86: Feat: Disable `Go to Programs` and `Save` buttons on Organization Profile page if user is not an organization representative.
**Is your feature request related to a problem? Please describe.**
At the moment for login user who is not an organization representative (has not declared that they are), when they go to `My Organization`, on the Organization Profile page they can try to click on the `Go to Programs` or `Save` buttons which should've been prevented.

**Describe the solution you'd like**
Disable the `Go to Prrograms` and `Save` buttons on Organization Profile page if login user is not (has not declared) an organization representative.

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ankitpal1029**
### Description

Go to Programs and Save buttons were appearing despite the user not declaring their organisation,
I accepted a responseStatus from the backend if it's value was 200 the above buttons are rendered, in all other cases it is not.
Fixes #86 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

I ran all the tests that were already written by running 
npm test
here is a screenshot of it being passed
testspassed

I ran the front end and replicated the situation (the new user has not declared any organisation in the my organisations page as shown below:(prior to changes)

before

after changes:

afterpr

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ankitpal1029** [comment]
@mtreacy002  i have run the tests and made a pull request with a different branch as you requested, kindly take a look

**Review by Aaishpra — COMMENTED** [review]
@ankitpal1029 can you link this PR to the issue by doing Fixes #122 
 also, the checkboxes can be ticked by doing [x]

**Comment by ankitpal1029** [comment]
@Aaishpra can you please explain what you mean by do Fixes 122, i though i was supposed to make a new pull request

**Comment by Aaishpra** [comment]
> @Aaishpra can you please explain what you mean by do Fixes 122, i though i was supposed to make a new pull request

i mean the pull request will be linked to the issue you have solved if you edit your PR (not any code) and write Fixes #122 

image


Something like this
Also the checkboxes will be ticked if you do [x] instead of [*]

**Comment by ankitpal1029** [comment]
ohh i see, i have linked the issue and made the checkbox have ticks 
i have linked it to issue #86 since #122 was my previous pull request that required changes

**Comment by Aaishpra** [comment]
> ohh i see, i have linked the issue and made the checkbox have ticks
> i have linked it to issue #86 since #122 was my previous pull request that required changes

good job, the PR looks nice now.

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@ankitpal1029, the `Go to Programs` button did became hidden when user has not declared they representing an organization, however, the button also diappeared for those who are onganization representative, which means there is a bug in the code. Can you please fix this?

* When user is not representative (expected behaviour)

Screen Shot 2020-10-27 at 2 43 58 pm

* when user is a representative and has created organization with few programs button also disappeared (not expected behaviour)
Screen Shot 2020-10-27 at 2 44 42 pm
Screen Shot 2020-10-27 at 2 50 38 pm
Screen Shot 2020-10-27 at 2 50 47 pm

**Comment by ankitpal1029** [comment]
@mtreacy002 I'll take a look at the issue , although i assumed the response message being 200 would be sufficient to render the save button when the user is part of an organisation

**Comment by mtreacy002** [comment]
> @mtreacy002 I'll take a look at the issue , although i assumed the response message being 200 would be sufficient to render the save button when the user is part of an organisation

@ankitpal1029 . For the issue you are working on ( #86 ), the user has not yet declared they representing an organization (response would be error 403 - HTTPStatus.FORBIDDEN). Hence, both `Go to Programs` and `Save` need to be hidden since they can't be allowed to create organization without that declaration. 
But, yes, you are right, when the response of the page request (GET /organization) is 200 (which means an organization is found since user who had declared they are a representative had created the organization) then both `Go to Programs` and `Save` buttons need to be shown. 
Issue #87 (fixed by #118 which already got merged)  on the other hand is dealing with when user has declared they represent organization but not yet created the organization (error 404 - HTTPStatus.NOT_FOUND). Which is why the `Save` button is given but the `Go to Programs` button is disabled until the organization is created. So, please integrate this code change (of #118) into your code.

Does this make sense?

**Comment by ankitpal1029** [comment]
@mtreacy002 i'm sorry i didn't respond the last few days , kind of swamped with assignments can i take a week to sort out these new changes

**Comment by mtreacy002** [comment]
> @mtreacy002 i'm sorry i didn't respond the last few days , kind of swamped with assignments can i take a week to sort out these new changes

Sure, @ankitpal1029 . Take your time. Just let me know when you have any issue. Good luck with your exam.

**Comment by ankitpal1029** [comment]
@mtreacy002 how am i supposed to make the user as representative for an organisation? i am having trouble replicating the error,



> * when user is a representative and has created organization with few programs button also disappeared (not expected behaviour)
> 
> Screen Shot 2020-10-27 at 2 44 42 pm
> 
> Screen Shot 2020-10-27 at 2 50 38 pm
> 
> Screen Shot 2020-10-27 at 2 50 47 pm

**Comment by mtreacy002** [comment]
> @mtreacy002 how am i supposed to make the user as representative for an organisation? i am having trouble replicating the error,
> 
> > * when user is a representative and has created organization with few programs button also disappeared (not expected behaviour)
> > 
> > Screen Shot 2020-10-27 at 2 44 42 pm
> > Screen Shot 2020-10-27 at 2 50 38 pm
> > Screen Shot 2020-10-27 at 2 50 47 pm

@ankitpal1029 , sorry for the late reply. To make a user a representative of an organization, you need to tick the box "I am a representative of an organization" under `My Space` > `Profile` > `Additional Info` (screenshot below)

Screen Shot 2020-11-27 at 2 59 09 pm

Only after this box is ticked, the user will be allowed to create an organization, then create a progrram. Does this make sense?

**Comment by mtreacy002** [comment]
@ankitpal1029 , I've just noticed there is a bug in the existing code from the recent merged which might cause you to get trouble replicating the error. I've opened issue #134 to fix this. I'll put this PR on hold for now and you can resume working on it once that issue 134 is done. Sorry for the hickups.

**Comment by ankitpal1029** [comment]
@mtreacy002  oh i see i'll take a look at this new issue and maybe try sorting it

**Comment by mtreacy002** [comment]
@ankitpal1029 . The bug on the navbar menu for My Space now is fixed through issue #152. You can continue with the issue here now. Please don't forget to pull the latest code from upstream develop branch 😉.

**Comment by mtreacy002** [comment]
@ankitpal1029 . Can you please givee an update? Are you still able to continue working on this? If not, I'll pass it on to other member so they can finish off the work.

**Comment by ankitpal1029** [comment]
@mtreacy002  i recently changed my laptop ,i have to set up the dev environment before working on this sorry for the delay in responding. Kindly allocate this issue to someone else as i am tied up with some work.

**Comment by mtreacy002** [comment]
> @mtreacy002 i recently changed my laptop ,i have to set up the dev environment before working on this sorry for the delay in responding. Kindly allocate this issue to someone else as i am tied up with some work.

Thanks for the update, @ankitpal1029. I'll relabel it as available then.

**Comment by mtreacy002** [comment]
Closing this pr now (see the post from contributor [above](https://github.com/anitab-org/bridge-in-tech-web/pull/123#issuecomment-780751272))

**Pull request closed without merging**
