### PR TITLE
Fixed all useEffect and unknown prop warnings

### LINKED ISSUE #140: Bug: Eslint warnings on the homepage
## Description
After running the app, there are a lot of eslint warnings from the rule `react-hooks/exhaustive-deps`. They are just warnings but can lead to bugs later as mentioned [here](https://github.com/facebook/create-react-app/issues/6880#issuecomment-485912528) by Dan Abramov. 

There are also some typo warnings like using `eventKey` instead of `eventkey` etc

## To Reproduce
**Steps to reproduce the behavior:**
1. Start the react app
2. While on homepage, open developer tools console
3. See the errors

## Screenshots
image

## Expected behavior
No errors and warnings should popup in the console.

### Update [Required]
- [ ] update useEffect's depedency array of the respective files.
- [ ] fix the typos cusing the warning.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1-2] hours

### PR DESCRIPTION
**Pull request by jalajcodes**
### Description

Fixed all the warnings listed in [this issue](https://github.com/anitab-org/bridge-in-tech-web/issues/140).

Fixes #140 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

No warning in console.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jalajcodes** [comment]
@mtreacy002 Created PR from a new branch. Sorry for the trouble, I should have done this the first time.

**Comment by mtreacy002** [comment]
> @mtreacy002 Created PR from a new branch. Sorry for the trouble, I should have done this the first time.

No worries, it's a common hiccups for new contributors. Will review as soon as I got time.

**Review by mtreacy002 — APPROVED** [review]
Well done, @jalajcodes for the fix.

I've tested this on the following environment.
OS: Mac OS Catalina v 10.15.7
Browser: Chrome 87.0.4280.141

Result:
Expected behaviour: The console should give no warnings.
Actual behaviour: As expected.

Screen Shot 2021-01-23 at 2 01 05 pm

Thanks, @jalajcodes for your contribution 🎉

**Comment by mtreacy002** [comment]
@jalajcodes , I've merged and closed this issue, but now I noticed there're other warnings shown on the console (not on initial run, but after user login). Any chance that these are caused by the change you've made on the useEffect()?

Screen Shot 2021-01-24 at 9 43 48 am

**Comment by mtreacy002** [comment]
Also, I just remembered there was a good reason why my mentor @meenakshi-dhanani and I chosed to use the empty [] as the useEffect() condition since the new change (using the value of fetch attribute inside the array) causes an infinite requests to backend that will definitely be very costly both to the users and organizations as it uses too much overhead (power consumption and network traffic).

ezgif com-gif-maker (25)

Whereas if we leave the condition as an empty array [], it will only send the request once, which is what we want.

ezgif com-gif-maker (26)

Do you have any suggestion on how to fix this? Should we just revert the change back (since they cause unnecessary high overhead which is more undesirable then having warnings)? Let me know what you think, @jalajcodes .

**Comment by 0xNilesh** [comment]
q1

We will see by considering one instance.

@mtreacy002 So, what really is happening there is that after putting requestPersonalBackground in the useEffect dependency array, it means that it will compare requestPersonalBackground every time the component re-renders and if its not equal, then it will execute again. In JS, if references of the two objects are same, then only it is considered as equal and whenever component re-renders requestPersonalBackground will be having new reference and that's why useEffect will execute again and again thus going into an infinite loop.

To resolve this and also remove the Eslint warning, we have two options :-

1> As requestPersonalBackground is constant, So, we can put requestPersonalBackground object in the useEffect and use access_token in the dependency array which also makes sense whenever access_token will be changed, useEffect will be executed.
q2

2> Another method is to remove Eslint warning but this isn't a good practice because future developers may be confused or create unexpected bugs without knowing linting is off.
q3

**Comment by jalajcodes** [comment]
@mtreacy002 As suggested above those mutiple requests to the backend can be fixed by moving the object inside useEffect. I'll have to check if any other files have similar problem and fix them too, should I make the changes and push to the same branch?

and about those errors after login, let me investigte their cause and get back to you.

**Comment by 0xNilesh** [comment]
@jalajcodes @mtreacy002 Yes all other files which are having useEffect have same issue and thing of after login is because all files which are using useEffect are only available to logged in users 😄.

**Comment by jalajcodes** [comment]
@mtreacy002 Okay so I fixed the multiple requests problem we were having.

But I am unable to reproduce those `unstable_FlushDiscreetUpdates` warnings you showed in the screenshot above. There are no errors in my console after login. Can you share the steps to reproduce the warnings?

**Comment by mtreacy002** [comment]
> @mtreacy002 As suggested above those mutiple requests to the backend can be fixed by moving the object inside useEffect. I'll have to check if any other files have similar problem and fix them too, should I make the changes and push to the same branch?

I think you would need to open a new issue for this, @jalajcodes since this PR has got merged.

> and about those errors after login, let me investigte their cause and get back to you.
 
Cool

**Comment by mtreacy002** [comment]
@jalajcodes . I was running the servers like normal, first I run BIT backend, then ms-backend-server, then the BIT frontend. As you can see in the gif below, console shows no warning before login but shows them after login.
ezgif com-gif-maker (27)

**Comment by jalajcodes** [comment]
@mtreacy002  Ok, I'll create a new issue for this.

Btw I did the same thing but, no warnings...maybe this was due to the multiple requests being sent and got fixed when I fixed that.

https://user-images.githubusercontent.com/17108695/105685021-a57b2980-5f1b-11eb-92db-7d33b1fe3e12.mp4

**Pull request merged**
