### PR TITLE
feat: Added AnitaBLogo on navbar

### LINKED ISSUE #13: AnitaB logo does not load on nav bar
**Describe the bug**
The AnitaB logo is not seen

**To Reproduce**
On the home page of the app

**Expected behavior**
Logo should be seen

**Screenshots**

Screen Shot 2020-06-04 at 3 31 45 PM

### PR DESCRIPTION
**Pull request by khushishikhu**
Description

Added AnitaBLogo on navbar

Fixes #13 

 Type of Change:

- Code
- User Interface

 Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

bit

### CODE REVIEW

**Comment by khushishikhu** [comment]
@meenakshi-dhanani  @mtreacy002  
please review my changes

**Comment by meenakshi-dhanani** [comment]
Looks good @khushishikhu ! Thank you so much. Continue to contribute 😊

**Review by meenakshi-dhanani — APPROVED** [review]

**Comment by meenakshi-dhanani** [comment]
@mtreacy002 if this looks good, can you approve?

**Comment by mtreacy002** [comment]
@meenakshi-dhanani . I faced this problem when trying to pull @khushishikhu 's pr branch. 

Screen Shot 2020-08-26 at 5 47 26 pm

Do you know how this might happen?

**Review by mtreacy002 — APPROVED** [review]
@khushishikhu and @meenakshi-dhanani . LGTM 👍. Well done, @khushishikhu . Thanks for contributing to the project.
Screen Shot 2020-08-26 at 5 58 26 pm

**Comment by mtreacy002** [comment]
Update @meenakshi-dhanani . I've tested and approve. Can you please merge this? Thanks.

**Comment by khushishikhu** [comment]
Thank you!! @meenakshi-dhanani  @mtreacy002  for approving my commits.

**Comment by mtreacy002** [comment]
You are most welcome, @khushishikhu . Look forward to your next contribution 😉😁

**Pull request merged**
