### PR TITLE
added description of the project

### LINKED ISSUE #203: Add project description in description meta tag in index.html
### Is your feature request related to a problem? Please describe.

Currently we have a description meta tag but the content doesn't contains the project description.
image

### Describe the solution you'd like

Adding content to description meta tag in index.html.

### Describe alternatives you've considered

NA

### Additional context

Project description can be found on project's readme or wiki.

### PR DESCRIPTION
**Pull request by shades-7**
### Description
Added project description in description meta tag in index.html 
Fixes #203

### Type of Change:

- Code

**Code/Quality Assurance Only**

### How Has This Been Tested?
Screenshot from 2021-04-08 13-17-20

### Checklist:

- [X] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by devkapilbansal — DISMISSED** [review]
LGTM :+1: 

Thanks @shades-7 for this

**Comment by devkapilbansal** [comment]
@anitab-org/maintainers please review it

**Review by HeroicHitesh — DISMISSED** [review]
@shades-7 Thanks for your contributions🎉
@devkapilbansal LGTM👍

**Review by epicadk — DISMISSED** [review]
👍🏼 looks good. Thankyou for your contribution

**Review by codesankalp — DISMISSED** [review]

**Comment by decon-harsh** [comment]
Instead of industries I would suggest you to use organizations as our model has this word. Moreover industry isn't appropriate with context to this. @shades-7



How about writing this? 

cc @devkapilbansal @epicadk @HeroicHitesh

**Comment by Amulya-coder** [comment]
Yes @decon-harsh you are right also if we see on the main page there also written the same description, Good observation 👏 @decon-harsh, @shades-7 please do the suggested changes mentioned by <b>decon-harsh</b>.

image

**Comment by shades-7** [comment]
Bridge-In-Tech is an application inspired by the existing AnitaB.org Mentorship System. It encourages organizations to collaborate with the mentors and mentees on mentoring programs.

 is this statement good for being description?

**Comment by Rahulm2310** [comment]
@mtreacy002 what do you suggest ?

**Comment by mtreacy002** [comment]
@shades-7 You can add an end of line comment inside a run.py (e.g. //Compulsory task - Setup environment) in the pr you're going to submit. Then once you submit the PR, inside that PR description you can add the screenshot under the "How this has been tested"). Does this make sense?

**Comment by shades-7** [comment]
> @shades-7 You can add an end of line comment inside a run.py (e.g. //Cumpolsory task - Setup environment) in the pr you're going to submit. Then once you submit the PR, inside that PR description you can add the screenshot under the "How this has been tested"). Does this make sense?

This file is a bridge in tech- web with on python file.

**Comment by mtreacy002** [comment]
Sorry, @shades-7  forgot that this is for frontend 🤣🤣. Then you can use that commented line in index.js for frontend perhaps? 😉

**Comment by shades-7** [comment]
> Bridge-In-Tech is an application inspired by the existing AnitaB.org Mentorship System. It encourages organizations to collaborate with the mentors and mentees on mentoring programs.
> 
> is this statement good for being description?

@mtreacy002 can you check this description too

**Comment by mtreacy002** [comment]
> @shades-7 You can add an end of line comment inside a run.py (e.g. //Compulsory task - Setup environment) in the pr you're going to submit. Then once you submit the PR, inside that PR description you can add the screenshot under the "How this has been tested"). Does this make sense?

I misplaced this comment. This is supposed to be posted on issue #218. Sorry for the confusion, @shades-7

**Comment by mtreacy002** [comment]
> Bridge-In-Tech is an application inspired by the existing AnitaB.org Mentorship System. It encourages organizations to collaborate with the mentors and mentees on mentoring programs.
> 
> is this statement good for being description?

This sounds right 👍

**Comment by shades-7** [comment]
@Amulya-coder can you review this?

**Review by epicadk — APPROVED** [review]
👍🏼 Looks good.

**Review by Amulya-coder — APPROVED** [review]
Great work @shades-7 🚀
Thank you for your contribution 🎉

**Review by HeroicHitesh — APPROVED** [review]

**Comment by Rahulm2310** [comment]
Added `Ready to merge` as we 3 approvals.
cc: @mtreacy002

**Comment by epicadk** [comment]
> Added `Ready to merge` as we 3 approvals.
> cc: @mtreacy002

You don't need to cc : ).

**Review by codesankalp — APPROVED** [review]

**Comment by mtreacy002** [comment]
@shades-7 , just one last change before I merge the PR.  Can you please replace the screenshot in the PR description under `How has this been tested?` to match the latest code change? Thanks 😉

**Comment by shades-7** [comment]
@mtreacy002 done.

**Review by Aaishpra — APPROVED** [review]

**Review by decon-harsh — APPROVED** [review]

**Review by mtreacy002 — APPROVED** [review]
Well done, @shades-7 for your work. Thank you for accommodating to the change requested and contributing to the project 🎉🎉🎉

**Pull request merged**
