### PR TITLE
Create config.yml

### LINKED ISSUE #66: Create the config.yml file for the Welcome Bot
## Description
 As a first time contributor,
 I need a bot to help guide my first contribution,
 so that I can follow this org's contribution guidelines.
 
 ## Mocks
 Screen Shot 2020-08-06 at 10 26 14 AM
 
 ## Acceptance Criteria
 ### Update [Required]
 * [ ]  newIssueWelcomeComment is complete with the correct links to this repo.
 * [ ]  newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
 * [ ]  firstPRMergeComment is complete.
 
 ## Definition of Done
 * [ ]  All of the required items are completed.
 * [ ]  Approval by 1 mentor.
 
 ## Estimation
 0.5 hours

### PR DESCRIPTION
**Pull request by aastha985**
### Description

Created config.yml file for the welcome bot to help first-time contributors. To activate the app you need to go to https://github.com/apps/welcome and click on install and give the app the required permissions.( Can only be done by a member of the org)

Fixes #66 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
I have tested the welcome bot with the same config.yml file in my personal repository. Here is a link to the repo: https://github.com/aastha985/WelcomeBot

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers , can I please ask your review on this because I have limited access as maintainer to this repository. Thanks in advance.

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@aastha985 . Just want to point out spelling mistakes on line 10 and 24 ("committed" instead of "comited").

**Comment by aastha985** [comment]
> @aastha985 . Just want to point out spelling mistakes on line 10 and 24 ("committed" instead of "comited").

Thank you for pointing it out :) I have corrected it 👍

**Review by mtreacy002 — APPROVED** [review]
Thank you, @aastha985 . This LGTM 👍

**Review by isabelcosta — APPROVED** [review]
Great work @aastha985 🎉 👏

**Comment by aastha985** [comment]
> Great work @aastha985 🎉 👏

Thank you!!

**Pull request merged**
