### PR TITLE
Fix: Fix repeated background on Homepage

### LINKED ISSUE #167: Bug: Repeating background on home page
**Describe the bug**
The background on home page is repeating on some screen sizes.

**To Reproduce**
1. Go to Developer Tools
2. Click on 'Toggle device toolbar'
3. Keep decreasing the screen width till the background repeats

**Expected behavior**
The background should not repeat on any screen size.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version: 84

### PR DESCRIPTION
**Pull request by arkumari2000**
### Description

Fixed the repeated background on the home page.

Fixes #167 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Screenshot 2021-02-24 at 8 04 49 PM
The bug is fixed and tested by running it on chrome as shown in the screenshot

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by devkapilbansal — CHANGES_REQUESTED** [review]
Please change your message as per commit message guidelines.
It should look like:-
```
fix:- Fixed repeat background
Closed #issueno
```

**Comment by mtreacy002** [comment]
> Please change your message as per commit message guidelines.
> It should look like:-
> 
> ```
> fix:- Fixed repeat background
> Closed #issueno
> ```

@devkapilbansal , as per the [Commit Message Guidelines](https://github.com/anitab-org/bridge-in-tech-backend/wiki/Commit-Message-Style-Guide), the body of a commit is optional and recommended for a complex commit. However, this pr is not a complex one so the title should be enough to xplain what this PR does. Plus, the issue that is closed by this PR does not need to be part of the commit message as it is mentioned inside the PR description.

**Comment by mtreacy002** [comment]
@chinmaym07 and @Rahulm2310 , can you please re-review/approve this PR? This is to replace PR #171 that you have reviewed and approved before.

**Review by Rahulm2310 — APPROVED** [review]
LGTM 💯

**Comment by Rahulm2310** [comment]
Changes Tested Locally 
Results:
`Expected Behaviour`: The background should not repeat on small screen sizes.
`Actual Behaviour`: as expected ✔️ 

bit-background-repeat-fix
 
Good Job @arkumari2000 🎉.Thanks for your contribution.

**Review by devkapilbansal — APPROVED** [review]
LGTM 👍

**Comment by devkapilbansal** [comment]
Changing label to `Ready to Merge` as testing is done above

**Review by mtreacy002 — APPROVED** [review]
Well done for your fix, @arkumari2000 and thank you for accommodating to the requested changes. Also thanks @Rahulm2310 and @devkapilbansal for your help with reviews and testing.

**Pull request merged**
