### PR TITLE
Doc: add all-contributors bot

### LINKED ISSUE #205: Doc: Add all-contributors bot configuration
## Description
As a maintainer,
I need to configure [all-contributors](https://allcontributors.org) bot,
so that I can better recognize contributors and leaders of this project.

https://allcontributors.org/docs/en/bot/configuration

### Update [Required]
- [ ] Add configuration to project https://allcontributors.org/docs/en/bot/configuration
- [ ] Add first contributors to table

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description

Add .all-contributorsrc for all-contributors bot

Fixes #205  

### Type of Change:
- Documentation

**Code/Quality Assurance Only**
- [x] New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
NA

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Cool!

**Comment by isabelcosta** [comment]
@mtreacy002 merged this with my admin privileges ;) I want to help you already recognize some of your contributors! For example @rpattath and Vuyanzi :)

**Comment by isabelcosta** [comment]
@all-contributors please add @Vuyanzi for design

**Comment by isabelcosta** [comment]
@all-contributors please add @mtreacy002 for maintenance, code, doc, userTesting and test

**Comment by Rahulm2310** [comment]
@allcontributors please add @Rahulm2310 for code, design, bug, mentoring and review

**Pull request merged**
