### PR TITLE
Doc:Add Zulip bage to README

### LINKED ISSUE #109: Doc: Add Zulip badge to README
## Description
As a contributor,
I need add the project Zulip channel to README,
so that I can clearly see where to go if I want to join the community Zulip Channel.

### Update [Required]
- [ ] Add Zulip badge to README with link to [#bridge-in-tech](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech) zulip channel 

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by madhhuurrii**
### Description

Added Zulip Badge to Readme file with icon
Fixes #109 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

image

### CODE REVIEW

**Comment by madhhuurrii** [comment]
@mtreacy002 Please check my PR

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@madhhuurrii , can you please move the badge to before the Bridge-In-Tech heading? Thanks

**Comment by madhhuurrii** [comment]
Okay!

**Comment by madhhuurrii** [comment]
Hii @mtreacy002, I have updated the requested changes

**Review by HeroicHitesh — APPROVED** [review]
@madhhuurrii LGTM 🎉
@mtreacy002 ready to merge.

**Review by mtreacy002 — APPROVED** [review]
LGTM to me too, @madhhuurrii . Thanks again for your contribution. 🎉

**Pull request merged**
