### PR TITLE
Fix: Maintain Login and Sign Up buttons layout on Register and Login pages regardless screen size

### LINKED ISSUE #142: Bug: Login and signup button overlaps
**Describe the bug**
Login and signup button overlaps in login page.

**To Reproduce**
1. Go to Home
2. Click on Login
3. See error

**Expected behavior**
Button should be inline with space between

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: none
 - OS: none
 - Browser none
 - Version none

### PR DESCRIPTION
**Pull request by nlok5923**
### Description

Manipulated the width percentage to a more accurate value 

Fixes #142 

### Type of Change:
Change in space between percentage 

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
testing login page:
BIT-Issue

testing register page:
bit-issue-2

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by nlok5923** [comment]
@mtreacy002 currently i had resolved issue for project development. but still i am investigating the cause. will definitely let you know once i got.

**Comment by nlok5923** [comment]
@mtreacy002 please review this pull request.

**Review by Ayush23Dash — CHANGES_REQUESTED** [review]
I think instead of hard coding width values(that makes it resistant to future changes) , we should remove .space-btw class from Login.jsx.
This completes the required changes without any hard coded values.

**Comment by nlok5923** [comment]
> I think instead of hard coding width values(that makes it resistant to future changes) , we should remove .space-btw class from Login.jsx.
> This completes the required changes without any hard coded values.

I had changed the hard-coded values to bootstrap classes please review again.

**Review by Rahulm2310 — COMMENTED** [review]
Looks fine now.

**Comment by Rahulm2310** [comment]
Although, I think as soon as any level of complexity is reached, the time expended overriding and fighting with Bootstrap would be better spent writing specific, focussed CSS and markup.

**Comment by nlok5923** [comment]
@mtreacy002 please review this pull request.

**Comment by mtreacy002** [comment]
@nlok5923 have you find out what cause the bug to come back from your last fix?

**Review by mtreacy002 — COMMENTED** [review]
@nlok5923 can you please provide some evidence under `How Has This Been Tested` in the issue description? A gif of the fix would be best. Thanks

**Comment by nlok5923** [comment]
> @nlok5923 have you find out what cause the bug to come back from your last fix?

yes @mtreacy002  i searched for reason and the reason must be of media query.

**Comment by nlok5923** [comment]
changes GIF:
BIT-Issue

**Comment by Rahulm2310** [comment]
@nlok5923 Please add this changes gif to PR description under 'How has this been tested'

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
Hi @nlok5923 , can you please make sure this behaviour is consistent across `Register` and `Login` page? Thanks

**Comment by nlok5923** [comment]
> Hi @nlok5923 , can you please make sure this behaviour is consistent across `Register` and `Login` page? Thanks

Thanks @mtreacy002. I investigated that the same error persist in register page too i had corrected it using bootstrap classses.

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@nlok5923 , the `Sign Up` button on both Login and Register page doesn't look right (the `Up` text got pushed to the bottom of `Sign` text). Can we make sure it stays as one level? If need to, you can adjust the middle space between the 2 buttons. 
ezgif com-gif-maker (29)

**Comment by nlok5923** [comment]
Sure @mtreacy002

**Comment by nlok5923** [comment]
changes in latest commit:
bit-isse04
Sorry the GIF is quite fast 
Register page
image

login page:
image

**Comment by nlok5923** [comment]
@mtreacy002  please review the pr.

**Comment by nlok5923** [comment]
@mtreacy002 please review the pull request i had made the requested changes.

**Comment by Rahulm2310** [comment]
@mtreacy002 just a suggestion. Can we remove the text underline from the blue buttons to make them consistent with green ones?

**Comment by mtreacy002** [comment]
> @mtreacy002 just a suggestion. Can we remove the text underline from the blue buttons to make them consistent with green ones?

Sure thing. @Rahulm2310 perhaps you can open a new issue on this one?  I'll label it a "First-timer only" issue

**Review by mtreacy002 — APPROVED** [review]
Well done, @nlok5923 for the fix. I've tested this PR locally. Below is the summary.
1. Code review: done
2. All possible responses are tested.
    Expected behaviour: The margin between `Login` and `Sign Up` buttons should be maintained regardless of screen size.
    Actual behaviour: As expected (see gif)
ezgif com-gif-maker (31)
3. Environment: 
    OS: macOS Catalina 10.15.7
    Browser: Chrome 88.0.4324.192

Thank you again for your contribution 🎉🎉🎉.

**Pull request merged**
