### PR TITLE
Fix#16 Remove .vscode

### LINKED ISSUE #16: Remove .vscode
## Description
.vscode should not be committed

## Acceptance Criteria
- [ ] Delete .vscode
- [ ] Add .vscode to .gitignore so that it is not added in the future

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

### PR DESCRIPTION
**Pull request by mahakbansal2019**
### Description

Remove .vscode

Fixes #16 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by mahakbansal2019** [comment]
@mtreacy002 Could you please review this.
Thanks :)

**Comment by mtreacy002** [comment]
This looks good to me, @mahakbansal2019 . Thanks for contributing. We just need to wait for one more reviewer to approve this PR before we can merge it 😉

**Comment by mtreacy002** [comment]
By the way, @mahakbansal2019, did you see my notes on issue #19? I need t move it across to backend since I mistakenly placed it in frontend. If you are still interested, here's the link for the same isse ([issue#55](https://github.com/anitab-org/bridge-in-tech-web/issues/19)) on backend.

**Review by mtreacy002 — DISMISSED** [review]
This looks good, @mahakbansal2019 . Thanks for contributing. 😁

**Comment by mtreacy002** [comment]
By the way, @mahakbansal2019 , can you please use the format available on the repository for this? Contributors are required to use the given template for consistency across the project. You can copy paste the template on to this PR description above to adopt the correct format. You can find the template for the PR [here](https://github.com/anitab-org/bridge-in-tech-backend/wiki/Getting-Started#start-working)

**Comment by mtreacy002** [comment]
I'm yet to update the frontend Wiki to match its backend repo. so, the mistake is mine that you didn't use the PR template. But if you could update it by modifying the PR description here, I would really appreciate your help 👍

**Comment by mtreacy002** [comment]
Just a question, @mahakbansal2019  . when you open the Pull Request, did it come with a template? It should have come automatically.

If so, please fill up the template where it is required. And please do not remove the subheadings so to maintain consistency across AnitaB projects. It will be a good learning experience for you to bring across different open source projects in the future 😄

**Comment by mahakbansal2019** [comment]
@mtreacy002 Sorry for not following the correct template.
I have updated the description.
Hope it's fine now :)
Will do the required updates if needed :)

**Comment by mtreacy002** [comment]
Perfect.... It looks much better now (more descriptive in terms of explaining the purpose of the PR). Thank you for the update, @mahakbansal2019

**Comment by meenakshi-dhanani** [comment]
You will also have to delete the .vscode directory that is already committed. .gitignore will ensure henceforth it doesn't get committed. But for the already committed one, can you delete it?

**Comment by mahakbansal2019** [comment]
I have deleted the .vscode directory.
Thanks, @meenakshi-dhanani for the review :)

**Review by meenakshi-dhanani — APPROVED** [review]
Thank you @mahakbansal2019 ! Looks good to me. Thank you so much for contributing. 
Since you have picked up a first timer issue, for the other issues, it would be nice if you involve the other community members :) That's also a way to contribute. And a very fulfilling one 😄

**Comment by meenakshi-dhanani** [comment]
@mtreacy002 Feel free to merge if it looks good

**Comment by mtreacy002** [comment]
Thanks, @meenakshi-dhanani . But I think only @anitab-org/bridgeintech-maintainers can merge a PR. The merge button is disabled on my side since I'm not authorised to merge 😁
Screen Shot 2020-06-16 at 12 29 16 am

**Comment by meenakshi-dhanani** [comment]
But I think you can approve, I can do the merging if necessary

**Review by mtreacy002 — APPROVED** [review]
Great work, @mahakbansal2019 👍 .

**Pull request merged**
