### PR TITLE
Fixed : Some Grammatical Errors in Readme

### LINKED ISSUE #90: Doc : Some Grammatical Error in Readme and Setup guide.
**Describe the bug**
Some Grammatical Errors in Readme and Setup guide.

**Screenshots for what changes should be added**
image
image
image

**Additional context**
Fixed them and linking a PR.

### PR DESCRIPTION
**Pull request by Aaishpra**
### Description
Some Grammatical Errors in Readme are fixed

Fixes #90 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by mtreacy002** [comment]
It's ok for now, @Aaishpra . I'll reassign you again then. But next time, can you please complete the issue you've already assigned to before requesting to work on another issue?

**Comment by Aaishpra** [comment]
Sure, My mistake

**Review by mtreacy002 — APPROVED** [review]
@Aaishpra, LGTM! Thank you for your correction on the doc 😉.

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers or @anitab-org/coding-team . Can someone please help review this PR? I've checked and given my approvall on this one. Thanks

**Comment by Aaishpra** [comment]
@mtreacy002 can I get assigned to other issues in this repository now or should I wait until these PRs get merged?

**Review by isabelcosta — APPROVED** [review]
Great catch @Aaishpra 👏

**Comment by mtreacy002** [comment]
@Aaishpra , feel free to claim another issue now. I'm going to squash and merge this PR.

**Pull request merged**
