### PR TITLE
Feat: Create and Update program page

### LINKED ISSUE #53: Create Program
## Description
As an organization,
I need to create a program,
so that I can provide progams for users to participate.

## Mocks
See mockup under https://github.com/anitab-org/bridge-in-tech-web/issues/7

### Update [Required]
- [ ] Must have the Create Program components as per initial mockup or with some adjustments that are approved by the mentors

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
2 - 3 days

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Add create and update Program page functionalities

Fixes #53, #78

### Type of Change:
- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
* to Create a program:
- login as a user that has is a representative of an organization and has created an organization
- go to `My Space` > `My Organization` > on the bottom left of the page, click `Go to Programs` > click on `Add Program` button
- fill the details on the Program Profile form page
- click submit
- on successful process, see response below

Screen Shot 2020-08-25 at 12 48 39 pm

* to Update a program: (WIP)
- Now view the program you've just created to make sure it's listed in the programs list (here my new program is Program B)
Screen Shot 2020-08-25 at 1 01 33 pm

- I then updated the program start and date date. On sucessful process, see message below
Screen Shot 2020-08-25 at 1 03 31 pm

- here's the list after the program was updated
Screen Shot 2020-08-25 at 1 05 26 pm

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @meenakshi-dhanani . Here's the PR for Create and update program (there are 2 issues open for this so I put both on the description as I'm not sure which one to select).
Notee: This is still a WIP. I'm currently stuck on submitting the form as the payload value for `payment_amount` is invalid. It got sent as a string instead of a number even though I already try to convert it to a number in the code.

Here's the snapshot of the payload

Screen Shot 2020-08-24 at 4 43 33 pm

The strange thing is it doesn't matter whether I used parseFloat or not, it's still showing as string `"1500"`

Screen Shot 2020-08-24 at 5 45 02 pm

**Comment by mtreacy002** [comment]
Update @meenakshi-dhanani . I've tried to put the data directly to backend swagger UI, and the error is on the `payment_amount` 
Screen Shot 2020-08-24 at 11 44 38 pm

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers and @meenakshi-dhanani. I've managed to solve the issue with `payment_amount` int value and date string format. Now user should be able to create program successfully. I'm going to work on the Update program now, using the same PR. So, will label this PR WIP.

**Comment by mtreacy002** [comment]
Update @meenakshi-dhanani and @anitab-org/bridgeintech-maintainers . I've confirm that the update in this PR already working. This PR is now complete. Can you please review? Thanks

**Review by foongminwong — COMMENTED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses were tested as below:

   * _Create and Update program page_  
    _Screenshot/gif/url_:  

     test-bit-web-pr-79-create-and-update-program-page


    _Expected Result_:  As a user, I shoudl be abe to create and update program as an organziation representative.
    _Actual Result_: Received an error `TypeError: programs.map is not a function`.

@mtreacy002 Attached is the screenshot of the error, hmm do you know what causes the problem?

test-bit-web-pr-79-create-and-update-program-page-error

**Comment by mtreacy002** [comment]
@foongminwong , can you tell me the steps you did to get to this error? starting from when you register the user who you've tested here.

**Comment by foongminwong** [comment]
> @foongminwong , can you tell me the steps you did to get to this error? starting from when you register the user who you've tested here.

Yes, the steps are:
Login -> MySpace -> My Organization -> Go to Programs -> ⚠

**Comment by mtreacy002** [comment]
can you please confirm that you have the same commit on the branch you're currently running as per the commit numbers on this branch:

the commits on the branch

Screen Shot 2020-08-27 at 11 32 53 pm

same as the terminal(top 3 commits):

Screen Shot 2020-08-27 at 11 33 26 pm

**Comment by foongminwong** [comment]
yup hmmm
test-bit-web-pr-79-git-log

**Comment by mtreacy002** [comment]
It's bit hard to read the commit numbers like that, @foongminwong . Can you please do it again by running 
> git log --oneline --graph

**Comment by foongminwong** [comment]
yeap, here you go:

test-bit-web-pr-79-git-log-graph

**Comment by mtreacy002** [comment]
@foongminwong , do you have time now to hop on hangout to troubleshoot the bug?

**Comment by meenakshi-dhanani** [comment]
ProgramCreateUpdate

I tried adding a program and updating it, both work!

**Review by meenakshi-dhanani — APPROVED** [review]

**Comment by mtreacy002** [comment]
@foongminwong . How did you go with your end? Are you able to solve the npm issue? Don't forget to also pulled the latest ms-backend-server from my fork repo that has new commits that fix GET /users/{user_id}, which was what causing the bug on @meenakshi-dhanani side when she tested pr #76. Let me know if you want to troubleshoot together like this morning. 😉

**Review by foongminwong — APPROVED** [review]

**Pull request merged**
