### PR TITLE
Doc: Delete issue template

### LINKED ISSUE #178: Doc: Delete .github/ISSUE_TEMPLATE folder
### Description
As a org admin / maintainer,
I need to maintain 1 version of issue templates used in the organization,
so that I can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Acceptance Criteria
**Update [Required]**

- [ ]  Delete .github/ISSUE_TEMPLATE

**Definition of Done**

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

**Estimation**
0.5 hours

### PR DESCRIPTION
**Pull request by shruti1421**
### Description

Deleted ISSUE_TEMPLATE folder present in .github 

Fixes #178

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Rahulm2310 — COMMENTED** [review]
@shruti1421 Please update the links to ISSUE_TEMPLATE in config.yml (line no. 11) and Contributing.md (point no. 11) with the common ISSUE_TEMPLATES under the new `.github` [repo](https://github.com/anitab-org/.github) by @isabelcosta .

Cc: @mtreacy002

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@shruti1421 , good job on the fix. Please don't forget to squash your commits into one 😉. Let me know if you need help with it.

**Comment by mtreacy002** [comment]
@shruti1421 , I still see 2 commits on this PR. Would you like to try again? I can give you a hint if you want to try. Alternatively, I can squash it at my end for you for now and that's ok as well 😉. Let me know what you feel like doing.

**Comment by shruti1421** [comment]
@mtreacy002 Actually, I've squashed all commits before updating my forked repo. So, after merging the updates it became 2 commits. After that, I've tried to squash but it's still showing same two commits. Let me try once again.

**Comment by shruti1421** [comment]
I tried to squash once again but it squashed all the previous commits also.

**Comment by Rahulm2310** [comment]
@shruti1421 You can try resetting to the previous state by running `git reset HEAD@{N}` where {N} represents the number of operations in reflog.

**Comment by mtreacy002** [comment]
@shruti1421 , I suggest you use `git rebase -i HEAD~{N}` instead.

**Review by mtreacy002 — DISMISSED** [review]
Well done, @shruti1421 for your work and thank you again for your contribution 🎉🎉🎉.

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@shruti1421 , just one more thing before I can approve this. Can you please resolve the conflicts? Thanks

**Comment by shruti1421** [comment]
Can I open a another PR for this issue because I'm not able to solve these conflicts.

**Comment by Rahulm2310** [comment]
@shruti1421 surely you can but I suggest you to continue with this PR as tackling these situations will help you learn a lot about git. It gets annoying sometimes but that also helps.

Also, I faced a similar situation in a recent PR where @mtreacy002 suggested to `git pull --rebase` and then squash commits which really helped in resolving conflicts.

**Comment by shruti1421** [comment]
I tried to reset the squash using all the methods which you have suggested above but was unable to solve this issue. I think, I might have used reset --soft HEAD~n  a lot many of times earlier and because of that I couldn't find which squash commit to reset. Therefore, I opened a new PR #189.
Even though I'm not able to solve this, I learned a lot about squashing git commands and how to reset it by searching through docs.Thank you so much for helping me out.

**Comment by keshakaneria** [comment]
@shruti1421 No worries! Its good that you learned some new concepts 😃 Closing this PR since [new PR](https://github.com/anitab-org/bridge-in-tech-web/pull/189) is opened with respect to this issue.

**Pull request closed without merging**
