### PR TITLE
benefit page created

### LINKED ISSUE #97: Feat: View Benefit page
## Description
As a public user,
I need see `Benefit` page,
so that I can read about the benefit becoming a member of BridgeInTech.

## Mocks
Based on the [target MVP](https://www.figma.com/file/jxCqu1lq55H7jC4FDY119a/BridgeInTech?node-id=10%3A1), add a content describing what the benefits are for becoming a member of BridgeInTech:
Screen Shot 2020-09-16 at 4 50 47 pm

### Update [Required]
- [ ] Add content to the `Benefit` page (sub menu under Home).
- [ ] Although the design is not the main focus, a reasonable layout is expected. 
- [ ] Avoid changing the Navbar layout in this PR as it is not required
### Enhancement to Update [Optional]
- [ ] Image can be taken from the source refered on the Figma MVP above or can be replaced with other imagee (IMPORTANT: Please be careful with copyright issue. Make sure you give a visual refence to the source of image).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 day

**Additional Information**
To do this task, you do not need to setup BridgeInTech Backend environment (if you haven't already done so), since there is no login required.

### PR DESCRIPTION
**Pull request by prathmeshkhandelwal1**
### Description

- Create Benefit.jsx in benefit folder in src directory.
- Added "/benefit" route in route.js

Fixes #97 

### Type of Change:

- Code
- User Interface

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### Screenshot of change
Screenshot (110)

### CODE REVIEW

**Comment by mtreacy002** [comment]
@prathmeshkhandelwal1, I noticed that you made the changes directly to your develop branch. This is not recommended as it will cause issue for you later on. Can you please create a branch for this (as mentioned in the [Getting Started wiki])(https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started) and open another PR? I'll close this one.

Screen Shot 2020-09-18 at 6 06 16 pm

**Comment by mtreacy002** [comment]
Also, instead of adding `benefit` folder, can you please add a folder called `home` under `src` folder (since the main Navbar here is `Home`) and move the Home.jsx into this folder as well. This way we'll have all pages under `Home` Menu (Home, About, and Benefit) inside this folder.

Be careful of the changes in files reference when you move the files. Make sure the routing still works.

**Comment by prathmeshkhandelwal1** [comment]
> Also, instead of adding `benefit` folder, can you please add a folder called `home` (since the main Navbar here is `Home`) and move the Home.jsx into this folder as well. This way we'll have all pages under `Home` Menu (Home, About, and Benefit) inside this folder.
> 
> Be careful of the changes in files reference when you move the files. Make sure the routing still works.

okkk...i will do all the changes and also sorry for this little mistake as i forgot to follow guidelines i will make sure this wont happen next time

**Comment by mtreacy002** [comment]
> > Also, instead of adding `benefit` folder, can you please add a folder called `home` (since the main Navbar here is `Home`) and move the Home.jsx into this folder as well. This way we'll have all pages under `Home` Menu (Home, About, and Benefit) inside this folder.
> > Be careful of the changes in files reference when you move the files. Make sure the routing still works.
> 
> okkk...i will do all the changes and also sorry for this little mistake as i forgot to follow guidelines i will make sure this wont happen next time

That's Ok, @prathmeshkhandelwal1 . It's good that you can learn the workflow 😉

**Comment by prathmeshkhandelwal1** [comment]
@mtreacy002 Can i close this PR as i created another one with separate branch?

**Comment by mtreacy002** [comment]
Yep, you can 👍

**Pull request closed without merging**
