### PR TITLE
[feat] Migrating documentation from github wiki to docusaurus

### LINKED ISSUE #186: Feat: Migrating documentation from github wiki to docusaurus
## Description

**Is your feature request related to a problem? Please describe.**
Current documentation is fine but with `docusaurus` , the documentation becomes more readable and maintainable.

**Describe the solution you'd like**
Moving the project's documentation to [docusaurus](https://v2.docusaurus.io).

**Additional context**
BIT backend has already migrated project documentation to docusaurus.

## Acceptance Criteria

- [ ] Move documentation to Docusaurus
- [ ] Deploy Docusaurus as part of GitHub pages - should be available at https://anitab-org.github.io/bridge-in-tech-web

### PR DESCRIPTION
**Pull request by codesankalp**
### Description

Added support for the migration of docs from wiki to docusaurus

Deployed URL: https://bridge-in-tech-web.surge.sh/

Fixes #186

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@codesankalp , the docusaurus looks good :+1: . It just need minor changes. As can be seen in the gif below, the `Edit this page` links (potentially in all pages, I only tested 3 here) atm direct us to `404 page not found`. Can you please link them to the relevant doc file inside the docusaurus folder? Thanks
ezgif com-gif-maker (56)

**Comment by codesankalp** [comment]
@mtreacy002 The page will not show 404 not found after merging of this PR.
As to edit this page the file must be present on develop branch which is possible after merging this PR.

For example, as the file is present in my docusaurus branch 
the URL is valid: 
https://github.com/codesankalp/bridge-in-tech-web/blob/docusaurus/docs/docs/Commit-Message-Style-Guide.md

but after merging this will be valid also:
https://github.com/anitab-org/bridge-in-tech-web/tree/develop/docs/docs/Commit-Message-Style-Guide.md

**Comment by mtreacy002** [comment]
> @mtreacy002 The page will not show 404 not found after merging of this PR.
> As to edit this page the file must be present on develop branch which is possible after merging this PR.
> 
> For example, as the file is present in my docusaurus branch
> the URL is valid:
> https://github.com/codesankalp/bridge-in-tech-web/blob/docusaurus/docs/docs/Commit-Message-Style-Guide.md
> 
> but after merging this will be valid also:
> https://github.com/anitab-org/bridge-in-tech-web/tree/develop/docs/docs/Commit-Message-Style-Guide.md

That makes sense. Ok, will approve it now as it looks good on my side. We just need to make sure that the issue disappears after merging 🤞 😉 .

**Review by mtreacy002 — APPROVED** [review]
LGTM, @codesankalp . Thank you for your contribution 🎉 🎉 🎉

**Comment by mtreacy002** [comment]
It works, @codesankalp . The `Edit this page` redirected to the relevant doc 🎉 💃  Thanks again for your contribution 😉

**Pull request merged**
