### PR TITLE
Fix: Redirect logged-in user to home when going to Register page through URL

### LINKED ISSUE #162: Bug: User can visit /register even after logged in
**Describe the bug**
Although, we remove the Register button form the UI when a user is logged in, still a logged in user can go to /register route from the url bar. 

**To Reproduce**
1. Go to Home page and login/register.
2. Go to /register route from url bar

**Expected behavior**
Once a user is logged in, they should not be able to visit register page by any way. 

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - Version :  88.0.4324.104

**Additional context**
Although, if we go to /login route it works as expected and redirects to home page. Register page should also work the same way. 

I would like to take up this issue.

### PR DESCRIPTION
**Pull request by Rahulm2310**
### Description

Currently a logged in user is allowed to visit the /register route from the search bar. With this PR I have made changes that would redirect the user to home page if they try to visit /register from the search bar. 
Fixes #162 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

I tried visiting /register route from the url bar but now it is redirected back to home page.
register-redirect

Also, all the existing test cases are passing successfully.
jest-test

### Checklist:

- [x] My PR follows the style guidelines of this project

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@Aaishpra @vj-codes @chinmaym07  Can you guys please review this PR. 🙂

**Review by chinmaym07 — COMMENTED** [review]
LGTM ..Good work !!

**Review by Aaishpra — COMMENTED** [review]
Code wise everything looks correct 💯 .
I will approve once someone tests this (would have tested this by myself but kind of swamped with school work) 😢
Although @Rahulm2310 good work by finding this bug and fixing it. 🎉

**Comment by chinmaym07** [comment]
I have tested this @Aaishpra locally . Can I just send my test-report .?

**Comment by Aaishpra** [comment]
> I have tested this @Aaishpra locally . Can I just send my test-report .?

Yes please @chinmaym07

**Comment by chinmaym07** [comment]
@Rahulm2310 while testing I found something new. please check.
when a user is logged in and he tries to go to /register route . He is redirected to homepage & at homepage if he clicks on logout button ,then he has to refresh it to get back the register and login button in place ...
Peek 2021-01-31 20-38

One small tweak is required .

**Comment by Rahulm2310** [comment]
Thanks @chinmaym07 for looking into it. 
I tried reproducing the issue using your steps and found that this happens not only after a user visits /register route. Even if I refresh the home page and try logout, then also logout doesn't happens. I tried console logging `isAuth` , seems that logout is not working. This only happens after refreshing the page. Before refresh, logout works as expected. 
bit-logout-issue

**Comment by chinmaym07** [comment]
Yes I know that ...I also looked into it ..its working correct before & after refresh it does not work the way as expected  ..because when you click on logout , the user is deleted from the cookies & I think it is not happening instantly that's why this error is there ..
You can set isAuth to true when user is logged and change isAuth to false when user clicks on logout . Try this ..It should work .
👍🏻 😀 @Rahulm2310

**Comment by Rahulm2310** [comment]
@chinmaym07 Thanks. I tried setting `isAuth` to false in the logout function and now it is working as expected. 
bit-logout-issue-fix
Please try this locally and confirm. Then I will push the changes here. 🙂

**Comment by chinmaym07** [comment]
Yes .It's working fine for me ..:+1:

**Comment by Rahulm2310** [comment]
@mtreacy002 @vj-codes can you please review this PR 🙂

**Comment by mtreacy002** [comment]
@Rahulm2310, can you please add a brief description of what this PR is about? It will help other contributors or reviewers to understand its purpose. 
Regardless, great work on finding the bug and submitting the fix. We just need one more reviewer to approve and someone too add another test report (after the update based on requested change) before I can merge this 😉.

**Comment by Rahulm2310** [comment]
@mtreacy002 Thanks! I have added a description, is it fine now ?

**Review by mtreacy002 — APPROVED** [review]
Thanks, @Rahulm2310 for your contribution 🎉. It looks good now so I'll approve it now. Also thanks @Aaishpra and @chinmaym07 for helping with review and test.

**Pull request merged**
