### PR TITLE
docs: Refactor useState() hooks to useReducer()

### LINKED ISSUE #217: Research: Refactor useState() hooks to useReducer()
### Is your feature request related to a problem? Please describe.

Currently we have a lot of separate useState() hooks in each component which makes them less maintainable. The idea is to refactor all the useState() hooks to a useReducer() hook.

### Describe the solution you'd like

Research about it. Discuss benefits/disadvantages, and if to be implemented, when is the best timing for refactoring to happen.

### Describe alternatives you've considered

NA

### Additional context

NA

### PR DESCRIPTION
**Pull request by HarshKumarChoudary**
### Description
Add  a docx file in bridge-in-tech-web/.github/issue#217 which solves the issue.

Fixes #217 

### Type of Change:

- Outreach/Research

### Description:

This is the link of research paper I prepared for fixing this issue and it can act as a support in development.
link:https://docs.google.com/document/d/1rQIwS6z5xqiRy-il5rkJeghvvIDpA1MYSAcEkihaVOc/edit?usp=sharing

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@HarshKumarChoudary No need to add the doc to `.github` folder. Please remove it. You just need to paste the link to the doc in the PR description (as you have correctly done).

**Comment by HarshKumarChoudary** [comment]
Removed the file.

**Review by Amulya-coder — COMMENTED** [review]
Looks good 👍

**Comment by devkapilbansal** [comment]
@mtreacy002 @Rahulm2310 Shouldn't RST or md format be used for this file instead of `.docx`

**Comment by Rahulm2310** [comment]
@devkapilbansal I don't see a problem with it. We have most of our documents in `.docx` format on wiki. We can create a `Research` category on wiki sidebar and add links to all these research docs under it. 
cc: @mtreacy002

**Comment by mtreacy002** [comment]
I agree with @Rahulm2310' point above, @devkapilbansal. Plus, another benefit keeping it in .docx is we can encourage discussions inside the docx itself (which will be the case with outreach/research topic), whereas having it as .md will limit this opportunity.

**Review by devkapilbansal — APPROVED** [review]
LGTM

**Review by HeroicHitesh — APPROVED** [review]
LGTM

**Comment by Rahulm2310** [comment]
@mtreacy002 Please add link to this doc in wiki.

**Review by Amulya-coder — APPROVED** [review]

**Comment by mtreacy002** [comment]
Just one minor request before I approve this, @HarshKumarChoudary . Can you please update the link with `Edit` access for everyone, so that anyone can add comment and continue with the discussions on the document you've shared.

**Comment by HarshKumarChoudary** [comment]
I had given Edit access to the file. Now anyone with link can edit it.

**Comment by mtreacy002** [comment]
Thank you, @HarshKumarChoudary . I'll approve this and close the pr without merge 😉

**Review by mtreacy002 — APPROVED** [review]
@HarshKumarChoudary , thank you for your suggestion on this issue 🎉🎉🎉. Will take it on board for now and further engage in discussion with you and everyone on this 😉.

**Comment by mtreacy002** [comment]
I've placed the doc on BIT web wiki under `Outreach/Research` topic.
Screen Shot 2021-04-10 at 6 04 14 pm

**Pull request closed without merging**
