### PR TITLE
fix : Fixed profile dropdown in navbar 

### LINKED ISSUE #134: Bug: Submenus under My Space > Profile dissappear from Navbar
**Describe the bug**
The submenus under My Space > Profile (Personal Detals, Additional Info, and Personal Background) have dissappeared from the Navbar. One of the recent merged to develop branch is suspected to have caused this.

**To Reproduce**
1. Run the 3 servers (BIT and MS backends as well as BIT frontend)
2. Login and try to update personal details (by going to My Space > Profile > Personal Details on the Navbar)
3. See error (when you click on Profile, dropdown options are not showing)

**Expected behavior**
When you click on Profile, the 3 dropdown options should've been given under the Profile tab instead)

**Screenshots**
with Bug (no options given when Profile is clicked)
Screen Shot 2020-12-13 at 10 39 54 pm

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.7
 - Browser: Chrome
 - Version ??

**Additional context**
The submenus options still exists as options under Navigation.js and Route.js. They are just not being displayed when the `Profile` tab is clicked.

### PR DESCRIPTION
**Pull request by chinmaym07**
### Description

Fixes #134 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Since it's a UI Bug in the Navbar , It is tested by running it locally.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

Attached a preview of the same fix.

Peek 2021-01-15 17-19

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@chinmaym07 hey, can I ask why 3 commits for 2 lines of change ?

**Comment by chinmaym07** [comment]
> @chinmaym07 hey, can I ask why 3 commits for 2 lines of change ?

I did a mistake by directly making the changes to develop branch of BIT-web .
Therefore I had to revert back the changes that I did to the develop branch and made a new branch "navbar-dropdown" & then committed & pushed the changes to that branch ,then I opened a PR that's why there are 3 commits. 😀 👍🏻

**Comment by mtreacy002** [comment]
@chinmaym07 , in the future, can you do a squash commit if you have more than one commit? Squashing the commits into one is the recommended practice, so it is a good thing to learn. For now, I'll squash them from my end.

**Review by mtreacy002 — APPROVED** [review]
Well done, @chinmaym07 for the fix.

I've tested this on the following environment:
OS: Mac OS Catalina v 10.15.7
Browser: Chrome v 87.0.4280.141 

Result:
Expected behaviour: when user login and click `My Space` > `Profile`, it should open the dropdown menu under Profile.
Actual behaviour: as expected

ezgif com-gif-maker (23)
 
Thank you @chinmaym07 for your contribution 🎉

**Pull request merged**
