### PR TITLE
Fix: Stop useEffect from sending multiple requests to the backend

### LINKED ISSUE #158: Bug: Multiple requests being sent to the server due to the change in useEffect's dependency array.
**Describe the bug**
Due to some changes made in [this PR](https://github.com/anitab-org/bridge-in-tech-web/pull/150) lots of requests are sent to the backend in a short amount of time.

**To Reproduce**
Steps to reproduce the behaviour:

1. Login with your account
2. Open Developer Console
4. Switch to the Network tab
4. Now, click on any link from the `My Space` dropdown present in the navbar.
3. See the requests increasing repeatedly on the bottom left side.

**Expected behaviour**
The number of requests should be equal to the number of fetch requests made by the page.

**Screenshots**
See multiple requests on the bottom left corner of the network tab.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by jalajcodes**
### Description
Modified the conflicting files by moving the additional info required by the fetch method inside the useEffect hook. This will prevent the respective components from rendering again, thus preventing continuous requests to the backend.

Fixes #158 

### Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Tested through the network tab of developer tools. The network requests are made to the backend to fetch only resources the current page needs, as shown in the below video.

https://user-images.githubusercontent.com/17108695/106255627-4c273900-6240-11eb-82ed-e1f380fe0e9d.mp4

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@jalajcodes Can you please post some screenshots or GIF showing the behavior after changes. That would really help a reviewer. Thanks 🙂

**Comment by jalajcodes** [comment]
@Rahulm2310 Added video to show the changes.

**Comment by jalajcodes** [comment]
@mtreacy002 it's on for review 🙂

**Comment by decon-harsh** [comment]
Squash the commits !

**Comment by jalajcodes** [comment]
> Squash the commits ! 

Don't they get squashed automatically on merge?

**Comment by decon-harsh** [comment]
> > Squash the commits ! 
> 
> Don't they get squashed automatically on merge? 

Idk I was told to do the same !! So i mentioned . Confirm it once

**Comment by vj-codes** [comment]
@decon-harsh @jalajcodes it is always a nice practice to squash the commits as mentioned in guidelines but if a contributor doesn't know how to do so, the maintainer can do it while merging.

**Comment by decon-harsh** [comment]
Thank you @vj-codes

**Comment by jalajcodes** [comment]
> @decon-harsh @jalajcodes it is always a nice practice to squash the commits as mentioned in guidelines but if a contributor doesn't know how to do so, the maintainer can do it while merging.

Cool I'll squash them then.

**Comment by jalajcodes** [comment]
Is it alright now? @decon-harsh @vj-codes

**Review by mtreacy002 — APPROVED** [review]
Well done, @jalajcodes for fixing the issue.
I've tested this code change and below is the summary:
1. Code review: Done
2. All possible responses were tested as below:
* Test PR 164 -> Resolves the issue on sending multiple requests to backend endpoint/s
**Expected behaviour:**
    The application must only send a single request to the relevant backend endpoint per "fetch" function
**Actual behaviour:**
    As expected
* Screenshot/gif/url:
ezgif com-gif-maker (30)

3. Test environment:
* OS: MacOs Catalina v 10.15.7
* Browser: Chrome v 88.0.4324.150

Thank you again, @jalajcodes for your contribution 🎉🎉.

**Pull request merged**
