### PR TITLE
Resolves the issue of not showing the option of logout

### LINKED ISSUE #153: Bug: No Option to Logout
**Describe the bug**

After successful login ,there is no option to logout & also Login button is still there but when I clicked on login again It showed the main landing page.

**Expected behavior**

After successful login ,there should be a button to logout & also Login button should not be there .

**Screenshots**

Peek 2021-01-22 15-38

I would like to work on this issue .

### PR DESCRIPTION
**Pull request by 0xNilesh**
### Description
Resolves the issue of not showing option for logout.

Fixes #153 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
I tried locally after logging in and logging out several times.

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by 0xNilesh** [comment]
@mtreacy002 Can you review this PR 😄.

**Review by Rahulm2310 — COMMENTED** [review]
Seems clean to me. Good job @VectoTec

**Review by chinmaym07 — COMMENTED** [review]
LGTM..Great 👍🏻

**Comment by mtreacy002** [comment]
Thank you @chinmaym07 and @Rahulm2310 for helping with the review. Now we need someone to help test the code change with a proper test report. An example of the test report can be seen [here](https://github.com/anitab-org/bridge-in-tech-web/pull/62#pullrequestreview-464955571)

**Comment by chinmaym07** [comment]
> Thank you @chinmaym07 and @Rahulm2310 for helping with the review. Now we need someone to help test the code change with a proper test report. An example of the test report can be seen [here](https://github.com/anitab-org/bridge-in-tech-web/pull/62#pullrequestreview-464955571)

I have tested the code locally then submitted a review for it . Can I submit a proper test report @mtreacy002 following the pattern shared above.?

**Review by chinmaym07 — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:

1) Code review - Done
2) All possible responses were tested as below:

      - Test PR 157 -> Resolves the issue of not showing the option of logout
      -  Screenshot/gif/url:
         test
      - Expected Result: As a user, When I login ,I should also be able to logout of the account on the BIT website as there is no logout button seen earlier.
      - Actual Result: Logout Button is visible as soon as the user is logged in.
      
 3) OS Version: Ubuntu 20.04

**Review by mtreacy002 — APPROVED** [review]
Well done, @VectoTec for solving the issue and thank you for your contribution 👍🎉🎉.
Also thank you @Rahulm2310 and @chinmaym07 for helping with the review and test 🎉🎉🎉

**Pull request merged**
