### PR TITLE
Added UI Screenshots in Readme

### LINKED ISSUE #120: Doc: Add existing UI screenshots to README.md
**Is your feature request related to a problem? Please describe.**
It would be ideal to see existing screenshots of all existing UIs.

**Describe the solution you'd like**
Create a section called UI screenshots inside README.md (under `Run the app` section) and place screenshots of all existing UIs.

**Describe alternatives you've considered**
Screenshots can be replaced with GIFs

**Additional context**
NA

### PR DESCRIPTION
**Pull request by amlannandy**
### Description

Added Screenshots for various sections of the App in the Readme, under 'Run The App' Section.

Fixes #120 

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by amlannandy** [comment]
@mtreacy002 Hello. Could you please review this PR?

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
Hi @amlannandy . Can you please make the changes on a new branch instead of the develop branch. This is mentioned in [point](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#start-working) 4 of the `Start Working` section on how to `Get started` with contribution. Thanks

**Comment by amlannandy** [comment]
> Hi @amlannandy . Can you please make the changes on a new branch instead of the develop branch. This is mentioned in [point](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#start-working) 4 of the `Start Working` section on how to `Get started` with contribution. Thanks

Ah I must have that. I don't think I can change the bracnh in this PR. Should I close this one and create a new PR instead?

**Comment by amlannandy** [comment]
@mtreacy002 Hey. I don't think I can change the branch in this PR. Should I close this one and create a new PR instead?

**Comment by mtreacy002** [comment]
> @mtreacy002 Hey. I don't think I can change the branch in this PR. Should I close this one and create a new PR instead?

Yep, I think that's the best idea (closing this one and open a new one). Let me know if you're facing trouble 😉

**Comment by amlannandy** [comment]
> > @mtreacy002 Hey. I don't think I can change the branch in this PR. Should I close this one and create a new PR instead?
> 
> Yep, I think that's the best idea (closing this one and open a new one). Let me know if you're facing trouble 😉

Okay. Will do that. Thanks! 😄

**Pull request closed without merging**
