### PR TITLE
Fix for Bug: Organizations list table content is overflowing outside …

### LINKED ISSUE #105: Bug: Organizations list table content is overflowing outside container
**Describe the bug**
The view page for organizations list doesn't look right. The table content is overflowing outside the table container.

**To Reproduce**
1. run the application
2. login as user
3. Click `Organizations` from the menu bar to view the list of organizations (note: make sure you have created at least one organization to view the organizations table)
4. See error (see screenshot section)

**Expected behavior**
The table content must be inside table container.

**Screenshots**
Screen Shot 2020-09-21 at 9 14 26 pm

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version ??

**Additional context**
NA

### PR DESCRIPTION
**Pull request by somayaj**
**Description**
The table width on the container-organizations css element has been changed to inherit instead of the specified width.

Fixes [#105](https://github.com/anitab-org/bridge-in-tech-web/issues/105) 

Type of Change:
Code

Bug fix (non-breaking change which fixes an issue)
How Has This Been Tested?
The integration tests were executed with the front end nodejs application

Checklist:
[X ] My PR follows the style guidelines of this project
 I have performed a self-review of my own code or materials
 I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
Code/Quality Assurance Only

[x ] My changes generate no new warnings

### CODE REVIEW

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@somayaj . I've tested this PR using Google Chrome browser with different screen sizes on the MacOS Catalina 10.15.7 machine.
Followings are my findings:

* on laptop HiDPI screen (1440 x 900)
Screen Shot 2020-10-18 at 9 36 53 pm
Note: the outer container of the table (form) spread across the width of the screen, it would be better if the outer container sits in the center with a margin instead of going full screen width. Also, the inner table container sits slightly to the left (not in the center) of the outer container 

* on laptop MDPI screen (1280 x 800)
Screen Shot 2020-10-18 at 9 37 11 pm
Note: the outer container still appears to go across the full width of the screen, but the inner container goes beyond the screen size (the table gets cut). However, the horizontal scrolling is not enabled.

* On laptop with touch (1280 x 950)
Screen Shot 2020-10-18 at 9 37 24 pm
Note: as per the MDPI laptop


**Conclusion:**

Ideally, the inner container should sit in the center of the outer container with a reasonable margin between theem. If the outer container width is less than the width of the screen, the outer container should sit in the center of the screen width.
 
When the outer/inner containers width are bigger than the screen width, then the horizontal scrolling should be enabled so the user can scroll to the right to see the content of the table that are not visible within the screen width.

Can you please make these adjustments?

**Comment by somayaj** [comment]
Hi Maya, just wanted to give you an update that I was able to get BIT and MS working here - the backend services. Should be able to move fast now for any other issues to resolve. Please assign if there are any. 

Thanks,
Asha

**Review by mtreacy002 — APPROVED** [review]
This PR is tested locally on MacOS Catalina 10.15.7 machine using Chrome browser with screen sizes 1440x900 (laptop HiDPI); 1280x800 (laptop MDPI); 1280x950 (laptop with touch)
The following is the test result:
* expected behaviour: 
    * outer container sits in the center of the screen width
    * the table is scrollable for any content that is overflowed outside the outer container
* actual behaviour: as expected
ezgif com-gif-maker (14)

Well done, @somayaj and thank you for your contribution 🎉🎉🎉

**Comment by somayaj** [comment]
Thanks!

**Pull request merged**
