### PR TITLE
feat(register): added password toggle + tests

### LINKED ISSUE #84: Feat: Add show/hide password toggle functionality on password fields
**Is your feature request related to a problem? Please describe.**
At the moment password field has no show/hide visibility option on the login and register form.

**Describe the solution you'd like**
Password fields need to have a show/hide visibility option so they can check their input on the field.

**Describe alternatives you've considered**
Open to contributor's idea as long as it fits the application well.

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ruppysuppy**
### Description

Added Password Toggle feature (Register Form)

Fixes #84 

### Type of Change:

- User Interface

### How Has This Been Tested?
Added automated tests

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

### CODE REVIEW

**Review by mtreacy002 — APPROVED** [review]
@ruppysuppy , great job on the toggle password feature. I've tested your code change and can confirm that the feature works with tests all passed. Thank you for your contribution to the project.

ezgif com-video-to-gif (8)

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers or @anitab-org/coding-team. Can someone else please review this PR? I've tested and approved the PR. Just need one more review and approval. Thanks beforehand.

**Review by techno-disaster — APPROVED** [review]
LGTM

**Review by mtreacy002 — APPROVED** [review]
LGTM too. Thanks for your contribution, @ruppysuppy

**Comment by mtreacy002** [comment]
> LGTM

@Techno-Disaster . Thank you for your review. Can you please change it as `Approve` instead of `comment`? This way it counts as approval so we can merge this PR.

**Review by annabauza — APPROVED** [review]

**Comment by annabauza** [comment]
It's seems to require review of owner. @mtreacy002 it's ready to merge

**Comment by mtreacy002** [comment]
> It's seems to require review of owner. @mtreacy002 it's ready to merge

Thanks for the review, @annabauza. I'll squash and merge it now. 😉

**Pull request merged**
