### PR TITLE
Feat: Logo redirects to homepage

### LINKED ISSUE #180: Feat: Redirect logo to homepage
**Is your feature request related to a problem? Please describe.**
Currently when a user clicks on the logo on the top left of the web UI, nothing happens.

**Describe the solution you'd like**
Add a link to the logo which redirects the user to homepage when clicked.

**Additional context**
ezgif com-gif-maker (4)

### PR DESCRIPTION
**Pull request by stableapple**
### Description

Logo redirects to homepage when clicked.

Fixes #180 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
When the logo is clicked, it redirects to homepage
ezgif com-gif-maker (3)

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@stableapple Thanks for your contribution. Just a suggestion, please don't create a PR in hurry just to prevent someone else claiming the issue. I think maintainers respect the fact that as contributors we want to contribute more & more to the project but be a little patient. Also, the creator of the issue always gets the first chance to claim it so don't worry. You will get ample chance. Good Luck 🙂 

Cc: @mtreacy002

**Comment by stableapple** [comment]
My apologies, I will take care of it next time.

**Comment by mtreacy002** [comment]
@stableapple, as per @Rahulm2310 says, please wait to be assigned next time. I'll let this one pass, but can you please follow the PR template and add the `How has this been tested` with explanation how you test this PR? For this type of issue, a gif would be best.
Screen Shot 2021-02-27 at 11 11 52 pm

**Comment by stableapple** [comment]
Okay sure, I'll do it ASAP.

**Comment by mtreacy002** [comment]
@stableapple , this PR #184 is for fixing issue #180, please change this in the isssue description.

**Comment by stableapple** [comment]
@mtreacy002 I have made the changes, can you please review it.

**Review by Rahulm2310 — APPROVED** [review]
LGTM 💯 . Thanks @stableapple

**Comment by Rahulm2310** [comment]
Changes Tested Locally
Results: 
`Expected Behaviour` : Clicking on logo should redirect to home page.
`Actual Behaviour`: as expected ✔️ 

bit-logo-link

**Review by mtreacy002 — APPROVED** [review]
Well done, @stableapple for your fix and thank you for your contribution. 🎉

**Pull request merged**
