### PR TITLE
repeat background fixed

### LINKED ISSUE #167: Bug: Repeating background on home page
**Describe the bug**
The background on home page is repeating on some screen sizes.

**To Reproduce**
1. Go to Developer Tools
2. Click on 'Toggle device toolbar'
3. Keep decreasing the screen width till the background repeats

**Expected behavior**
The background should not repeat on any screen size.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome
 - Version: 84

### PR DESCRIPTION
**Pull request by arkumari2000**
### Description

Fixed the repeated background on some screen size

Fixes #167 

### Type of Change:

- Code
- Quality Assurance
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
This screenshot is taken in the screen size where background image was repeating.
Screenshot 2021-02-06 at 9 08 20 PM

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Rahulm2310 — DISMISSED** [review]
Good Job @arkumari2000 🎉

**Comment by mtreacy002** [comment]
Thank you @arkumari2000 for submitting the PR, and thank you @Rahulm2310 to help with the review. Now we only need one more approval from other reviewer, then move ahead with testing.

**Review by chinmaym07 — APPROVED** [review]
LGTM.  Good work @arkumari2000 thankyou for your contribution.!!

**Review by chinmaym07 — DISMISSED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses were tested as below:

   - Test PR 171 -> Resolves the issue of repeating background image

   -  Screenshot/gif/url:
  
Screen Shot 2021-02-17 at 21 01 59

  -  Expected Result: One Background image should not repeat on lower screen widths.
  -  Actual Result: On lower screen widths as the size of the window decreases , background image size also reduces which results in multiple image being presented on the screen. But only one image should be rendered .

3. OS Version: Ubuntu 20.04

   -  Browser : Firefox

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
@arkumari2000 , did you make any dependency changes for this PR? I could see the `package-lock.json' is included in this commit. This is unnecessary file to be included, so, can you please exclude it from the commit? 
Also, I noticed that you made the changes directly to develop branch which is not recommended (refer to the guideline [Getting Started > Start Working > point 4](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#start-working) - screenshot below). Can you please fix this? Thanks
Screen Shot 2021-02-18 at 12 52 20 pm

cc @Rahulm2310 and @chinmaym07

**Comment by arkumari2000** [comment]
@mtreacy002 Although I didn't made any changes with package.lock.json, I guess it was automatic according to the new versions and all. But I have deleted that file from my commit is it okay now? Or I have to do it another way?

**Review by mtreacy002 — CHANGES_REQUESTED** [review]
Oh no... @arkumari2000 you misunderstood what I meant with removing it from the commit. You don't need to delete the file from the existing code, instead, you must opt to not include the file inside your commit (by clicking on the discard changes icon on the right side of this particular file from VSCode). 
Good news is, the deletion only affecting your fork develop branch, so you can pull from the upstream develop to get the file to fix the damage. 
Another thing is, you still need to write the code change on a separate new branch. Once you've done that you can close this PR as any change made directly to develop branch cannot be merged. Hope I've made this clearer now?

**Comment by devkapilbansal** [comment]
@mtreacy002 although it is a good practice to use separate branches for pull requests but there is no harm in pull requests made directly from the default branch. It creates problems only when contributors work on more than one issue at a time.
Would it be good to close the PR and reopen it just because it from default branch? :thinking:

**Comment by mtreacy002** [comment]
@devkapilbansal, the request is made following the guidelines set in AnitaB Open Source. I'm pretty sure AnitaB would want it if the contributors keep the consistency across all projects as much as we can with the GitHub workflow, squash commit, and working on a separate branch on issue instead of default branch, which is why they set the contributing guidelines 😉. cc @anitab-org/admins

**Comment by mayburgos** [comment]
I don't quite understand what the issue is, but Maya is correct. We ask that you create branches from the default and name it with intention and good naming practices in mind (i.e. updatingUIButton, refactoringHomePage, etc). It is a common practice in many industries, just like some orgs ask you to rename the branch to match the issue # you're working on. 

Otherwise, when we look at our metrics it's like every single change is coming from 1 branch. I don't know of anyone who does work from only 1 branch like this unless they're on a solo project and don't really care. 🤷🏼 

If we can improve our contribution guidelines to be more clear, please let us know. We're always looking to improve. 

Other admins can comment on the issue. 👍🏼

**Comment by mtreacy002** [comment]
Thank you, @mayburgos for your confirmation. @arkumari2000 . You can close this PR and resubmit the code changes from a new separate branch. @chinmaym07 and @Rahulm2310 can re-approve once you've done this. Thanks.

**Comment by arkumari2000** [comment]
> Thank you, @mayburgos for your confirmation. @arkumari2000 . You can close this PR and resubmit the code changes from a new separate branch. @chinmaym07 and @Rahulm2310 can re-approve once you've done this. Thanks.

Okay, I will do that.
Thanks for the help.

**Pull request closed without merging**
