### PR TITLE
Issue12 add travis ci to frontend

### LINKED ISSUE #12: Setup Travis CI to run tests for BIT React frontend
## Description
As a developer,
I need run tests on every PR on CI,
so that I can immediately get feedback on a build

## Out of Scope
Deploying to a higher environment when the push is on the develop branch

## Acceptance Criteria
- [ ] Build gets triggered on push
- [ ] Tests run for build

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1-2 hours

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description

This PR is to add travis CI and test cases for Register user functionality.

Fixes #12 

### Type of Change:
- Code
- Quality Assurance

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected) 

**Additional Note**
- Travis CI is added before writing test cases. Failed result is expected.

### CODE REVIEW

**Comment by meenakshi-dhanani** [comment]
Why are there changes to other files besides travis.yml in this PR? I would expect a few test cases and travis.yml change here only, not the other files

**Comment by mtreacy002** [comment]
Sorry, posted the comment on a wrong PR. 🤣

**Comment by mtreacy002** [comment]
@meenakshi-dhanani, you will see this a lot during GSoC. Don't be alarmed and thinking I did unnecessary changes 🤣.  When I created this PR, the changes to my Register UI hasn't been merged to develop branch, so when I pushed, it still has the original boilerplate from the create-react-app. You can see it from the commit history.

Screen Shot 2020-06-19 at 9 15 37 am

**Comment by mtreacy002** [comment]
And I created the PR branch out of the develop branch at the time (which was already contains the boilerplate) which is I believe the correct way to do (not branching out of Register UI PR branch). Plus, this was OK (not branching out from other working PR) since I don't need any other code related to travis. Different case when I branched out from Basic setup code to Register UI code that needs the basic setup code to work on. Hope this makes sense.

**Comment by mtreacy002** [comment]
Ok, I removed the boilerplate files now. Can you please review this now, @meenakshi-dhanani ?

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers and @meenakshi-dhanani . Atm travis is failing since there is no tests found in the PR (I haven't written one yet and have deleted the boilerplate including the App.js and App.test.js as suggested). Will you be able to merge this as it is or do you want me to write one Register test case on the same PR here?

**Comment by meenakshi-dhanani** [comment]
Okay I can see the build is passing for the test case. I have some feedback on the test case, but that I will discuss in the test case PR.


Screen Shot 2020-06-19 at 9 26 50 PM

**Review by meenakshi-dhanani — APPROVED** [review]

**Comment by meenakshi-dhanani** [comment]
@foongminwong can you approve if all seems fine?

**Comment by mtreacy002** [comment]
> Okay I can see the build is passing for the test case. I have some feedback on the test case, but that I will discuss in the test case PR.
> 
> Screen Shot 2020-06-19 at 9 26 50 PM

Yeah, I've fixed it and gave update on [zulip](https://anitab-org.zulipchat.com/#narrow/stream/237630-bridge-in-tech/topic/New.20Issues/near/201348960). just forgot to give update here. ;P

**Comment by mtreacy002** [comment]
@anitab-org/bridgeintech-maintainers . I'll need to do some clean up on this PR git branch so it won't carry unnecessary files to develop branch. So @meenakshi-dhanani and @foongminwong , please review it again after my cleanup.

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . I have cleaned up my PR branch. I'm closing this PR and replace it with PR #25

**Pull request closed without merging**
