### PR TITLE
Fix: prevents protected routes from redirecting to homepage when refreshed

### LINKED ISSUE #168: Bug: Refreshing protected routes redirects to home page
**Describe the bug**
Refreshing protected routes redirects to home page

**To Reproduce**
1. Go to http://localhost:3000/members
2. Refresh the page
3. You are redirected to home page

**Expected behavior**
After refresh, user should remain on the same page and not redirected to home page.

**Screenshots**
bit-refresh-error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84

### PR DESCRIPTION
**Pull request by stableapple**
### Description

Prevents the protected routes to redirect to homepage when the page is refreshed.

Fixes #168 

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
ezgif com-gif-maker

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by decon-harsh** [comment]
### Tested Locally, 

Test220

Protected routes are not getting redirected to homepage on being refreshed , moreover unprotected routes like about section are also not getting redirected to homepage.

@Rahulm2310 @stableapple  is this a requested feature as well?

**Comment by Rahulm2310** [comment]
This happens due to the fact that `isAuth` is initialized with false in the AuthContext because of which the protected routes redirects to home page. @stableapple thanks for the solution. Although, I think we don't need to conditionally handle it in ProtectedRoute component. The problem lies in AuthContext and should be solved there. A solution I tried is to initialize `isAuth` this way : `const [isAuth, setIsAuth] = useState(Cookies.get('user')!=null);` .Not sure it is the best way but it is cleaner.
@mtreacy002 what do you say?

**Comment by mtreacy002** [comment]
@Rahulm2310 I think the gif shown by @decon-harsh has the expected behaviour which is the protected routes didn't get redirected to Homepage upon refresh. The impact of the unprotected route also didn't get redirected to Homepage IMO although not mentioned in the issue description is also expected. I think the solution given here by @stableapple is fine. What do you all think?

**Comment by Rahulm2310** [comment]
@mtreacy002 The solution by @stableapple is correct. I was just suggesting a more cleaner solution.

**Comment by mtreacy002** [comment]
> @mtreacy002 The solution by @stableapple is correct. I was just suggesting a more cleaner solution.

@Rahulm2310 as you mentioned this can be addressed in AuthContext, perhaps we can open an issue to address this? Or if you would prefer @stableapple to make the change in this pr, please post a change request as part of your review 😉.

**Review by Rahulm2310 — COMMENTED** [review]
@shades This can be fixed in the `AuthContext.js`.  Just initialize the `isAuth` state the following way and it would work.
`const [isAuth, setIsAuth] = useState(Cookies.get('user')!=null);`.

**Review by Rahulm2310 — COMMENTED** [review]
@stableapple Remove the `ProtectedRoute.js` file from your commit as these changes are not needed.

**Comment by stableapple** [comment]
I have made the changes. Can you please review it?

**Review by Rahulm2310 — APPROVED** [review]
LGTM 💯

**Review by mtreacy002 — APPROVED** [review]
Well done for the fix, @stableapple . I've tested this locally.
Here's the test report.
1. Code review: Done
2. Tested all possible outcomes.
    Expected behaviour: Once logged-in, user can move to any protected pages and refresh the pages without redirecting back to homepage.
    Actual behaviour: As expected (see gif below)
ezgif com-gif-maker (48)


3. Environments:
    OS: MacOS Catalina 10.15.7
    Browser: Google Chrome

Thank you again for your contribution to the project 🎉🎉🎉

**Pull request merged**
