### PR TITLE
research task for remote hosting

### LINKED ISSUE #216: Research: Using gh-pages as remote frontend
### Is your feature request related to a problem? Please describe.

We need to deploy our frontend to a hosting service (ideally free)

### Describe the solution you'd like

Research about hosting the project (frontend) on `gh-pages` (discuss possibility, benefits/disadvantages, and potential issues).

### Describe alternatives you've considered

NA

### Additional context

NA

### PR DESCRIPTION
**Pull request by shades-7**
### Description
research on deployment of frontend to a hosting service 

Fixes #216

### Type of Change:

- Code
- Outreach

### How Has This Been Tested?
[Research](https://docs.google.com/document/d/1E4O-Ro6c-z1WkYy6FcLsfsg813YXRSy-PN6Iy7cmmOk/edit?usp=sharing)

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
-

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by shades-7** [comment]
@mtreacy002 @Rahulm2310 Can you just check this for once, as I was not sure about how to send PR for research issues?

**Comment by mtreacy002** [comment]
@shades-7 . What you've done is what's expected from the Outreach/Research issue (you've added your suggestion as a google doc link in this PR description. I'll label this `Need Review` now so that others can give their feedback on your approach 😉.

**Comment by shades-7** [comment]
@jalajcodes can you please review it?

**Comment by shades-7** [comment]
@mtreacy002 @Rahulm2310 since OSH is coming to end soon, I was wondering if you can review it and let me know if I have to make any changes?

**Comment by Rahulm2310** [comment]
@shades-7 The doc looks good. Only thing I feel is that there should be more information on why gh-pages/netlify should or should not be used and `why it would be a perfect fit for our app` rather than info on how to deploy the app on gh-pages or Netlify.

**Comment by jalajcodes** [comment]
@shades-7 Nicely done, +1 for the comparison you showed in the end...

Now just address what Rahul said above and it'll be good to go.

**Comment by shades-7** [comment]
> @shades-7 The doc looks good. Only thing I feel is that there should be more information on why gh-pages/netlify should or should not be used and `why it would be a perfect fit for our app` rather than info on how to deploy the app on gh-pages or Netlify.

@Rahulm2310 i have updated the doc. please review

**Review by Rahulm2310 — APPROVED** [review]
Looks good 🎉. Thanks @shades-7.
@mtreacy002 we can now add the link to this research doc in wiki.

**Comment by shades-7** [comment]
> Looks good 🎉. Thanks @shades-7.
> @mtreacy002 we can now add the link to this research doc in wiki.

Thank you 🙂

**Review by mtreacy002 — APPROVED** [review]
Good job, @shades-7 . Thank you for your contribution 🎉 🎉 🎉 . Approving and closing this issue now as the document has been added to the BIT web wiki > Outreach/Research sections 😉 .

**Pull request closed without merging**
