### PR TITLE
resolved test conflict

### LINKED ISSUE #239: Bug: Test failed after Link tag is used to replace anchor tag in Register.jsx and Login.jsx
### Describe the bug
Recent commit #231 which refactored `anchor <a> tag` to `<Link>` causes tests to fail for Login.test.jsx and Register.test.jsx. 

### To Reproduce
1. Run test
2. See errors

### Screenshots
Screen Shot 2021-04-24 at 9 58 22 am
 
### Desktop (please complete the following information):
 - OS: MacOS Catalina 10.15.7
 - Browser: Safari

### Additional context
Other errors also exist. If possible address the issue at the same time.

### PR DESCRIPTION
**Pull request by shades-7**
### Description
Resolved the conflict arising in testing due to changing Link tag with achor tag.

Fixes #239 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
Screenshot from 2021-04-27 13-26-51

### Checklist:

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by shades-7** [comment]
@Rahulm2310 @mtreacy002 have a look please

**Comment by mtreacy002** [comment]
@shades-7 , all 3 tests are passing which is what we want. @jalajcodes and @Rahulm2310 , can we fix the warnings as a separate issues or you prefer to tackle it here?

Screenshots of the error warnings
image
image

**Comment by jalajcodes** [comment]
@mtreacy002 

`can't perform a react state update on an uncomunted component...` 
This will require changing some things in the register component's code.

`An update to PersonalDetails inside test was not wrapped inside a act().....`
This usually indicates that we didn't test everything in the component. To fix it we'll have to figure out where in the code it is coming from.

If @shades-7 is up for it, let's fix these here otherwise we can always create another issue.

**Comment by Rahulm2310** [comment]
@mtreacy002 @jalajcodes @shades-7 I agree with Jalaj. It would be better to fix all the warnings here itself.

**Comment by shades-7** [comment]
I would love to solve this, but since I have no experience in testing, if you all can assist it will be great.🙂

**Comment by jalajcodes** [comment]
> I would love to solve this, but since I have no experience in testing, if you all can assist it will be great.🙂


Sure, that's why we are here. Now do you have an idea on how to tackle the first warning or do you need a hint?

**Comment by shades-7** [comment]
> > I would love to solve this, but since I have no experience in testing, if you all can assist it will be great.🙂
> 
> Sure, that's why we are here. Now do you have an idea on how to tackle the first warning or do you need a hint?

I will need hint @jalajcodes

**Comment by devkapilbansal** [comment]
> > > I would love to solve this, but since I have no experience in testing, if you all can assist it will be great.slightly_smiling_face
> > 
> > 
> > Sure, that's why we are here. Now do you have an idea on how to tackle the first warning or do you need a hint?
> 
> I will need hint @jalajcodes

Pinging @jalajcodes @mtreacy002 again

**Comment by mtreacy002** [comment]
@shades-7 and @devkapilbansal , I'm still new with React so I might not be able to answer this correctly. I'm assuming that @jalajcodes suggesting to add new test to be written/adjusted to match the changes in the personal details page. @jalajcodes or @Rahulm2310 perhaps can confirm this 😉

**Comment by mtreacy002** [comment]
@devkapilbansal and @shades-7, IMO we can approve and merge this PR as it is since the actual issue (failing tests) has been addressed. We can address the warnings issue on a separate PR because it is more important to make sure the next PR that comes after this will pass the tests. Let me know what you think.

**Comment by devkapilbansal** [comment]
I agree with you @mtreacy002 
We can discuss about this in a new issue

**Review by mtreacy002 — APPROVED** [review]
Approving this PR now. Will open a separate issue to tackle warnings 😉 . Thank you @shades-7 for your contribution to the project 🎉 🎉 🎉 .

**Pull request merged**
