### PR TITLE
Setup

### LINKED ISSUE #218: Task: Set up local environment
## Description
As a contributor
I need to set up local environment for bridge-in-tech-web and send screenshots,
so that I can provide proof of the same.

## Mocks
NA

### Update [Required]
- [ ] Set up local environment
- [ ] Provide a **gif** of a successful login attempt that must show the change on main navbar before and after login.
 
      **Before login**
Screen Shot 2021-03-30 at 8 46 13 am

      **After login**
Screen Shot 2021-03-30 at 8 46 35 am

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Additional note:**
**1. This is a compulsory task that must be completed before contributors can claim other Open Source Hack issues.
2. The PR that is sibmitted for this task will counted towards the `Documentation/Training` category of Open Source Hack.**. To do this you can create a new branch called `setup` and add an end of line comment inside the index.js (e.g. //Compulsory task - Setup environment) so git pick up a change in the code base. Then once you submit the PR, inside that PR description you can add the gif under the "How this has been tested").

### PR DESCRIPTION
**Pull request by shades-7**
### Description
Compulsory task - Setup environment
Fixes #218

### Type of Change:
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
BIT

### Checklist:
- [X] I have performed a self-review of my own code or materials
- [X] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by shades-7** [comment]
@mtreacy002 can you review this?

**Comment by mtreacy002** [comment]
> @mtreacy002 can you review this?

@shades-7 , can you please replace the .mp4 to a gif file just as you've done [here](https://github.com/anitab-org/bridge-in-tech-web/issues/218#issuecomment-811843995). The .mp4 shows as broken link on safari.

Screen Shot 2021-04-09 at 1 52 46 pm

**Comment by decon-harsh** [comment]
> > @mtreacy002 can you review this?
> 
> @shades-7 , can you please replace the .mp4 to a gif file just as you've done [here](https://github.com/anitab-org/bridge-in-tech-web/issues/218#issuecomment-811843995). The .mp4 shows as broken link on safari.
> 
> Screen Shot 2021-04-09 at 1 52 46 pm
> 

Should she upload a gif instead of mp4?

**Comment by mtreacy002** [comment]
@decon-harsh , I believe that's the best 😉

**Comment by shades-7** [comment]
> @decon-harsh , I believe that's the best

done

**Review by mtreacy002 — APPROVED** [review]
Well done, @shades-7 , thank you for accommodating for the requested change. Will approve and close this issue now 😉.

**Pull request closed without merging**
