### PR TITLE
Feat: Issue#36 view user personal background

### LINKED ISSUE #36: View Profile - Personal Background
## Description
As a registered user,
I want to view my personal background details,
so that I can see if they are the latest.

## Mocks
#5 

## Acceptance Criteria
- [ ] Display details related to personal background as per the mockup - gender, age, ethnicity, sexual orientation, religion, physical ability, mental ability, socio economic, highest education, years of experience
- [ ] Add unit tests that test if these fields are displayed

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

### PR DESCRIPTION
**Pull request by mtreacy002**
### Description
Add View User Personal Background

Fixes #36 

### Type of Change:
- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
- login, then go to My Space > Profile > Personal details (so backend can retrieve user_id) > Personal background.
Expect to see personal background data (providing you have created one on BIT backend Swagger UI)

ezgif com-video-to-gif (2)

### Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mtreacy002** [comment]
Update @anitab-org/bridgeintech-maintainers . Here's the PR for View user's personal background functionality. Please review when you have time. Thanks

**Review by foongminwong — DISMISSED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done 

2. All possible responses were tested as below:

   * _View User Personal Background_  
     _Screenshot/gif/url_: 
       
       test-bit-pr-44-view-personal-background

     _Expected Result_:  As a user, I should be able to view my `Personal Background`
     _Actual Result_: Same as expected.

3. OS Version: Windows 10

**Comment by mtreacy002** [comment]
@foongminwong . Thanks heaps for the approval. Howevere, I've just push forced a code change since I pull rebased and applied the same requested changes from the previous PR. Can you please re-approved? Sorry.

**Review by foongminwong — DISMISSED** [review]

**Review by meenakshi-dhanani — DISMISSED** [review]
Reviewed the code with @mtreacy002, almost the same as the previous component. 
Please check it out - @ramitsawhney27 @foongminwong

**Review by meenakshi-dhanani — APPROVED** [review]

**Review by foongminwong — APPROVED** [review]

**Pull request merged**
