### PR TITLE
Fix for Bug: Organizations list table content is overflowing outside …

### LINKED ISSUE #105: Bug: Organizations list table content is overflowing outside container
**Describe the bug**
The view page for organizations list doesn't look right. The table content is overflowing outside the table container.

**To Reproduce**
1. run the application
2. login as user
3. Click `Organizations` from the menu bar to view the list of organizations (note: make sure you have created at least one organization to view the organizations table)
4. See error (see screenshot section)

**Expected behavior**
The table content must be inside table container.

**Screenshots**
Screen Shot 2020-09-21 at 9 14 26 pm

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version ??

**Additional context**
NA

### PR DESCRIPTION
**Pull request by somayaj**
…container #105

Fixes #105 [](https://github.com/anitab-org/bridge-in-tech-web/issues/105). The table width on the container-organizations css element has been changed to inherit instead of the specified width. 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?
The integration tests were executed with the front end nodejs application 

### Checklist:
- [X ] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x ] My changes generate no new warnings

### CODE REVIEW

**Comment by mtreacy002** [comment]
@somayaj , can you please add more words to the description of the PR? It is important that each PR has it's own description so that other contributors can quickly grasp information about the PR without having to move away from the page (so, the link to the issue as you place in replacement of the PR description is not an ideal method).  The link to the issue is still needed in the `Fixes` information.

**Comment by mtreacy002** [comment]
Also, can you please add screenshots of the target UI page under the `How has this been tested?` section to confirm that the required changes have been made?

**Comment by somayaj** [comment]
> @somayaj , can you please add more words to the description of the PR? It is important that each PR has it's own description so that other contributors can quickly grasp information about the PR without having to move away from the page (so, the link to the issue as you place in replacement of the PR description is not an ideal method). The link to the issue is still needed in the `Fixes` information.

done

**Comment by somayaj** [comment]
> Also, can you please add screenshots of the target UI page under the `How has this been tested?` section to confirm that the required changes have been made?

The front end client project was built and the json was mocked up since I couldn't get the backend servers to be up. The front end layout appears to overlay the content.

**Comment by mtreacy002** [comment]
> > @somayaj , can you please add more words to the description of the PR? It is important that each PR has it's own description so that other contributors can quickly grasp information about the PR without having to move away from the page (so, the link to the issue as you place in replacement of the PR description is not an ideal method). The link to the issue is still needed in the `Fixes` information.
> 
> done



> > @somayaj , can you please add more words to the description of the PR? It is important that each PR has it's own description so that other contributors can quickly grasp information about the PR without having to move away from the page (so, the link to the issue as you place in replacement of the PR description is not an ideal method). The link to the issue is still needed in the `Fixes` information.
> 
> done

@somayaj , can you please keep the headings of the PR template so that we maintain the consistency across the repo? An example of a proper PR description can be seen on the other open PR as per screenshot below

Screen Shot 2020-10-16 at 2 51 20 pm

**Comment by mtreacy002** [comment]
I think the PR title can also be simplified to avoid title goes inside PR description box like in your case here.

**Comment by mtreacy002** [comment]
> > Also, can you please add screenshots of the target UI page under the `How has this been tested?` section to confirm that the required changes have been made?
> 
> The front end client project was built and the json was mocked up since I couldn't get the backend servers to be up. The front end layout appears to overlay the content.

May I know the issue you're facing when trying to setup the backend? Perhaps we can troubleshoot this together. It will be useful when later in the future you are working on frontend issues that dependent on backend api endpoint consumption.

**Comment by mtreacy002** [comment]
Another thing, @somayaj . Can you please create a new branch to work on the issue and send PR from there instead of making the change on the develop branch? It is mentioned in the `Getting Started` guideline section [`Start working`](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#start-working) step 4 as the expected workflow when working with an issue.

**Comment by somayaj** [comment]
Hi Mary, was getting a 403 when trying to push the branch to origin. That's
why I forked it. I tried it again now and I get the same error.' can't seem
to push my local to origin.

Asha

**Comment by mtreacy002** [comment]
@somayaj . As per the [Getting Started guideline](https://github.com/anitab-org/bridge-in-tech-web/wiki/Getting-Started#start-working), you do need to fork, clone and remote the repo. You can check this by running the command as per screenshot below (1st command shows the repo has no upstream, then the next one is adding the upstream and shows what the repo is tracking after setting the remote).
remote

Once you have done this, for any issue you are working on, you should create a new branch for that issue (so don't work directly on the develop branch). This way when you are pushing the PR, it should allow you to do so. 
Can you please try this?

**Comment by somayaj** [comment]
Absolutely! thanks for the info.

**Comment by somayaj** [comment]
done

**Comment by mtreacy002** [comment]
Thank you Somaya, for accommodating the requested change. I will close this issue here and continue giving the review on PR #121 you've just opened 😉

**Pull request closed without merging**
